// ─── QA SQL Challenges ────────────────────────────────────────────────────────

export const CHALLENGES = [
  // ── HR Challenges ──────────────────────────────────────────────────────────
  {
    id: 'hr-1',
    schema: 'hr',
    title: 'Karyawan Terlambat',
    category: 'Data Validation',
    difficulty: 'easy',
    description: 'QA Task: Validasi fitur absensi. Temukan semua karyawan yang pernah datang terlambat (status = "late"). Tampilkan nama karyawan dan tanggal keterlambatannya.',
    hint: 'JOIN tabel employees dengan attendance menggunakan employee_id',
    solution: `SELECT e.name, a.date, a.clock_in FROM attendance a JOIN employees e ON a.employee_id = e.id WHERE a.status = 'late' ORDER BY a.date;`,
    validate: (rows) => rows.length === 2 && rows.every(r => r.status === undefined || true),
  },
  {
    id: 'hr-2',
    schema: 'hr',
    title: 'Email Duplikat Karyawan',
    category: 'Duplicate Detection',
    difficulty: 'easy',
    description: 'QA Task: Bug dilaporkan — sistem registrasi karyawan membiarkan email duplikat. Temukan email yang digunakan lebih dari satu karyawan.',
    hint: 'Gunakan GROUP BY email HAVING COUNT(*) > 1',
    solution: `SELECT email, COUNT(*) as count FROM employees GROUP BY email HAVING COUNT(*) > 1;`,
    validate: (rows) => rows.length === 0,
  },
  {
    id: 'hr-3',
    schema: 'hr',
    title: 'Cuti Tanpa Persetujuan',
    category: 'Business Logic',
    difficulty: 'medium',
    description: 'QA Task: Validasi alur approval cuti. Cari semua cuti yang berstatus "approved" tetapi kolom approved_by masih NULL (tidak ada approver). Ini seharusnya tidak boleh terjadi.',
    hint: 'WHERE status = "approved" AND approved_by IS NULL',
    solution: `SELECT lr.*, e.name as employee_name FROM leave_requests lr JOIN employees e ON lr.employee_id = e.id WHERE lr.status = 'approved' AND lr.approved_by IS NULL;`,
    validate: (rows) => rows.length === 0,
  },
  {
    id: 'hr-4',
    schema: 'hr',
    title: 'Total Gaji per Departemen',
    category: 'Aggregation',
    difficulty: 'medium',
    description: 'QA Task: Verifikasi laporan payroll. Hitung total gaji per departemen dan bandingkan dengan budget yang tersedia. Tampilkan nama departemen, total gaji, budget, dan selisihnya.',
    hint: 'JOIN employees dengan departments, GROUP BY, lalu hitung budget - total_salary',
    solution: `SELECT d.name, SUM(e.salary) as total_salary, d.budget, d.budget - SUM(e.salary) as remaining FROM departments d LEFT JOIN employees e ON d.id = e.department_id WHERE e.status = 'active' GROUP BY d.id, d.name, d.budget ORDER BY total_salary DESC;`,
    validate: (rows) => rows.length > 0,
  },
  {
    id: 'hr-5',
    schema: 'hr',
    title: 'Karyawan Tidak Pernah Absen',
    category: 'Data Integrity',
    difficulty: 'hard',
    description: 'QA Task: Verifikasi data absensi. Temukan karyawan aktif yang SAMA SEKALI tidak memiliki record attendance (mungkin ada bug di sistem pencatatan absensi).',
    hint: 'Gunakan LEFT JOIN atau NOT IN / NOT EXISTS',
    solution: `SELECT e.id, e.name, e.department_id FROM employees e LEFT JOIN attendance a ON e.id = a.employee_id WHERE a.id IS NULL AND e.status = 'active';`,
    validate: (rows) => rows.length > 0,
  },

  // ── E-Commerce Challenges ──────────────────────────────────────────────────
  {
    id: 'ec-1',
    schema: 'ecommerce',
    title: 'Pelanggan Email NULL',
    category: 'Data Validation',
    difficulty: 'easy',
    description: 'QA Task: Validasi form registrasi. Seharusnya email wajib diisi. Temukan pelanggan yang tidak memiliki email (NULL).',
    hint: 'WHERE email IS NULL',
    solution: `SELECT id, name, phone, city FROM customers WHERE email IS NULL;`,
    validate: (rows) => rows.length === 1,
  },
  {
    id: 'ec-2',
    schema: 'ecommerce',
    title: 'Email Pelanggan Duplikat',
    category: 'Duplicate Detection',
    difficulty: 'easy',
    description: 'QA Task: Bug dilaporkan — sistem memungkinkan dua akun dengan email yang sama. Temukan email yang digunakan oleh lebih dari satu customer.',
    hint: 'GROUP BY email HAVING COUNT(*) > 1, join kembali ke tabel customers untuk detail',
    solution: `SELECT email, COUNT(*) as count, GROUP_CONCAT(name, ', ') as names FROM customers WHERE email IS NOT NULL GROUP BY email HAVING COUNT(*) > 1;`,
    validate: (rows) => rows.length === 1,
  },
  {
    id: 'ec-3',
    schema: 'ecommerce',
    title: 'Produk Stok Nol Tapi Aktif',
    category: 'Business Logic',
    difficulty: 'easy',
    description: 'QA Task: Validasi tampilan produk. Produk dengan stok 0 tidak boleh bisa dipesan. Temukan produk yang masih aktif (is_active=1) tetapi stok = 0.',
    hint: 'WHERE stock = 0 AND is_active = 1',
    solution: `SELECT id, name, category, price, stock FROM products WHERE stock = 0 AND is_active = 1;`,
    validate: (rows) => rows.length === 1,
  },
  {
    id: 'ec-4',
    schema: 'ecommerce',
    title: 'Order Total Tidak Sesuai',
    category: 'Calculation Validation',
    difficulty: 'medium',
    description: 'QA Task: Validasi perhitungan total order. Bandingkan total_amount di tabel orders dengan jumlah kalkulasi dari order_items (quantity * unit_price). Temukan order yang nilainya tidak cocok.',
    hint: 'JOIN orders dengan SUM(quantity * unit_price) dari order_items, lalu bandingkan',
    solution: `SELECT o.id, o.total_amount, SUM(oi.quantity * oi.unit_price) as calculated, o.total_amount - SUM(oi.quantity * oi.unit_price) as diff FROM orders o JOIN order_items oi ON o.id = oi.order_id GROUP BY o.id HAVING diff != 0;`,
    validate: (rows) => rows !== null,
  },
  {
    id: 'ec-5',
    schema: 'ecommerce',
    title: 'Pelanggan Most Valuable',
    category: 'Aggregation',
    difficulty: 'medium',
    description: 'QA Task: Verifikasi fitur laporan pelanggan. Temukan 5 pelanggan dengan total pembelian (status completed) terbesar. Tampilkan nama, total order, dan total belanja.',
    hint: 'JOIN customers dengan orders WHERE status="completed", GROUP BY customer, ORDER BY total DESC LIMIT 5',
    solution: `SELECT c.name, COUNT(o.id) as order_count, SUM(o.total_amount) as total_spent FROM customers c JOIN orders o ON c.id = o.customer_id WHERE o.status = 'completed' GROUP BY c.id, c.name ORDER BY total_spent DESC LIMIT 5;`,
    validate: (rows) => rows.length <= 5,
  },
  {
    id: 'ec-6',
    schema: 'ecommerce',
    title: 'Order Item Tanpa Produk Valid',
    category: 'Data Integrity',
    difficulty: 'hard',
    description: 'QA Task: Verifikasi integritas data. Cari order_items yang merujuk ke product_id yang tidak ada di tabel products (foreign key violation).',
    hint: 'LEFT JOIN order_items ke products, cari WHERE products.id IS NULL',
    solution: `SELECT oi.* FROM order_items oi LEFT JOIN products p ON oi.product_id = p.id WHERE p.id IS NULL;`,
    validate: (rows) => rows.length === 0,
  },

  // ── Banking Challenges ─────────────────────────────────────────────────────
  {
    id: 'bank-1',
    schema: 'banking',
    title: 'NIK Duplikat Nasabah',
    category: 'Duplicate Detection',
    difficulty: 'easy',
    description: 'QA Task: Validasi registrasi nasabah. NIK (nomor identitas) harus unik per nasabah. Temukan NIK yang digunakan lebih dari satu kali.',
    hint: 'GROUP BY nik HAVING COUNT(*) > 1',
    solution: `SELECT nik, COUNT(*) as count, GROUP_CONCAT(name, ', ') as names FROM customers WHERE nik IS NOT NULL GROUP BY nik HAVING COUNT(*) > 1;`,
    validate: (rows) => rows.length === 1,
  },
  {
    id: 'bank-2',
    schema: 'banking',
    title: 'Rekening Tanpa Nasabah Valid',
    category: 'Data Integrity',
    difficulty: 'easy',
    description: 'QA Task: Verifikasi integritas data. Cari rekening yang customer_id-nya tidak ada di tabel customers.',
    hint: 'LEFT JOIN accounts ke customers, cari WHERE customers.id IS NULL',
    solution: `SELECT a.* FROM accounts a LEFT JOIN customers c ON a.customer_id = c.id WHERE c.id IS NULL;`,
    validate: (rows) => rows.length === 0,
  },
  {
    id: 'bank-3',
    schema: 'banking',
    title: 'Saldo Tidak Konsisten',
    category: 'Calculation Validation',
    difficulty: 'hard',
    description: 'QA Task: Audit saldo rekening. Bandingkan saldo saat ini (accounts.balance) dengan saldo terakhir dari riwayat transaksi (balance_after dari transaksi terakhir). Temukan rekening yang tidak konsisten.',
    hint: 'Gunakan subquery atau CTE untuk mendapatkan balance_after dari transaksi terakhir tiap rekening',
    solution: `SELECT a.id, a.account_number, a.balance as current_balance, t.balance_after as last_txn_balance FROM accounts a JOIN (SELECT account_id, balance_after FROM transactions WHERE id IN (SELECT MAX(id) FROM transactions GROUP BY account_id)) t ON a.id = t.account_id WHERE a.balance != t.balance_after;`,
    validate: (rows) => rows !== null,
  },
  {
    id: 'bank-4',
    schema: 'banking',
    title: 'Pinjaman Jatuh Tempo',
    category: 'Business Logic',
    difficulty: 'medium',
    description: 'QA Task: Verifikasi fitur reminder pinjaman. Tampilkan semua pinjaman yang sudah jatuh tempo (due_date < today) tetapi statusnya masih "active" (belum closed atau overdue).',
    hint: 'WHERE status = "active" AND due_date < date("now")',
    solution: `SELECT l.*, c.name as customer_name FROM loans l JOIN customers c ON l.customer_id = c.id WHERE l.status = 'active' AND l.due_date < date('now') ORDER BY l.due_date;`,
    validate: (rows) => rows !== null,
  },
  {
    id: 'bank-5',
    schema: 'banking',
    title: 'Transaksi Rekening Inactive',
    category: 'Business Logic',
    difficulty: 'medium',
    description: 'QA Task: Validasi aturan bisnis. Rekening dengan status "inactive" seharusnya tidak bisa melakukan transaksi. Cari transaksi yang terjadi pada rekening inactive.',
    hint: 'JOIN transactions dengan accounts WHERE accounts.status = "inactive"',
    solution: `SELECT t.*, a.account_number, a.status FROM transactions t JOIN accounts a ON t.account_id = a.id WHERE a.status = 'inactive' ORDER BY t.created_at;`,
    validate: (rows) => rows.length > 0,
  },
];
